import type { Metadata } from "next";
import {Hind} from 'next/font/google'
import "./globals.css";
import Footer from "@/component/Footer";
import Header from "@/component/Header"
const hind = Hind({
  weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={hind.className}>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
